module.exports = {
  /** Movie Actions **/
  GET_MOVIES: 'GET MOVIES',
  QUERY_MOVIES: 'QUERY MOVIES',
  CREATE_MOVIE: 'CREATE MOVIE',
  DELETE_MOVIE: 'DELETE MOVIE',
  SET_ACTIVE_MOVIE: 'SET ACTIVE MOVIE'
};
